### ISSUE TITLE
Failed to load the pp-markdown package

### ISSUE THREAD

**Issue by drtconway** [skandasoft/pp-markdown#3]
To reproduce, install the `pp-markdown` package via the usual mechanism.

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.6
**Thrown From**: [pp-markdown](https://github.com/skandasoft/pp-markdown) package 0.0.2

### Stack Trace

Failed to load the pp-markdown package

```
At Unexpected token 'export'

/Users/tom.conway/.atom/packages/pp-markdown/node_modules/marked/lib/marked.esm.js:2667
export { Lexer, Parser, Renderer, Slugger, TextRenderer, Tokenizer, defaults, getDefaults, lexer, marked, options, parse, parseInline, parser, setOptions, use, walkTokens };
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:84:7)
    at NativeCompileCache.runInThisContext (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:148814)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149668)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at /packages/pp-markdown/lib/pp-markdown.coffee:2:10)
    at /packages/pp-markdown/lib/pp-markdown.coffee:1:1)
    at /packages/pp-markdown/lib/pp-markdown.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at requireModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1195620)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3402605)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3389145
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3387945)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3388718)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:384186)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382914)
    at PackageManager.atom.packages.loadPackage (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:527:32)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:385486)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:915033
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:909639)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1194943)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1195031
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1193699)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
 20x -9:51.3.0 core:backspace (input.hidden-input)
     -8:50.2.0 editor:newline (input.hidden-input)
     -2:55.1.0 editor:fold-current-row (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
ide-haskell 2.7.0 
ide-typescript 0.9.5 
language-cpp14 0.6.2 
language-groovy 0.7.0 
language-haskell 1.23.0 
pp-markdown 0.0.2 
```

**Comment by einarkjellback** [comment]
I have the exact same error message when trying to install. I use MacOS 12.0.1.

**Comment by krausce** [comment]
Me as well - Ubuntu 20.04.1
